### ISSUE TITLE
database password with slash

### ISSUE THREAD

**Issue by sblondeau** [WildCodeSchool/symfony-dev-deploy#1]
Database password are randomly generated. 
It doesn't work if the password has a slash, ex : "x54m/lo1t". In this case, there is an error when we use the symfony console.
Avoid special characters like / or % in these passwords

**Comment by RomainFallet** [comment]
Fixed https://github.com/WildCodeSchool/symfony-dev-deploy/commit/1468f0543e9a12433be8a175aa62d57e11ac500b.
