### ISSUE TITLE
apache rewriting

### ISSUE THREAD

**Issue by sblondeau** [WildCodeSchool/symfony-dev-deploy#2]
Ajouter les directives pour la réecriture d'URL directement dans le fichier de configuration apache (ce qui évite d'avoir à install apache-pack) et est plus optimisé

**Comment by RomainFallet** [comment]
@sblondeau De quelles réécritures as-tu besoin ? Ou plutôt, quelles réécritures ne marchent pas déjà ?

**Comment by RomainFallet** [comment]
@sblondeau J'ai suivi la config apache suggérée par Symfony, si tu as des soucis avec les réécritures, n'hésite pas à faire remonter !
