### ISSUE TITLE
sshpass password

### ISSUE THREAD

**Issue by sblondeau** [WildCodeSchool/symfony-dev-deploy#4]
quand tu utilises sshpass dans le workflow github, il faut entourer le password par des doubles quotes car sinon ça plante si le password commence par un caractère spécial.

donc à modifier en `sshpass -p "${{ secrets.SSH_PASS }}"  ssh -tt ...`

**Comment by RomainFallet** [comment]
@sblondeau 👍  https://github.com/WildCodeSchool/symfony-dev-deploy/commit/493f15109e11e618872bbb398d40a06d28e0b08a
